version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=PROD_SECRET_KEY_HERE

  frontend:
    build:
      context: .
      dockerfile: frontend_web/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
