// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6rX6a3BCoSOxKjU9lra0Dz7_2cqFgNI',
    appId: '1:450035263910:web:fe4fd9700756702ba60767',
    messagingSenderId: '450035263910',
    projectId: 'health-ml-app',
    authDomain: 'health-ml-app.firebaseapp.com',
    storageBucket: 'health-ml-app.firebasestorage.app',
    measurementId: 'G-J5WPQ9EB0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbwSl0dGx_x3u3OCm0ztHMFNn1DdLz5Q',
    appId: '1:450035263910:android:eb5cf1a8debbc929a60767',
    messagingSenderId: '450035263910',
    projectId: 'health-ml-app',
    storageBucket: 'health-ml-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHanWGHxB3Y6kI7H7TXJi7LbpTov6Vxqs',
    appId: '1:450035263910:ios:18beeb287c8e5f4ea60767',
    messagingSenderId: '450035263910',
    projectId: 'health-ml-app',
    storageBucket: 'health-ml-app.firebasestorage.app',
    iosBundleId: 'com.example.frontendMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHanWGHxB3Y6kI7H7TXJi7LbpTov6Vxqs',
    appId: '1:450035263910:ios:18beeb287c8e5f4ea60767',
    messagingSenderId: '450035263910',
    projectId: 'health-ml-app',
    storageBucket: 'health-ml-app.firebasestorage.app',
    iosBundleId: 'com.example.frontendMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM6rX6a3BCoSOxKjU9lra0Dz7_2cqFgNI',
    appId: '1:450035263910:web:5b37c98cadeee1cfa60767',
    messagingSenderId: '450035263910',
    projectId: 'health-ml-app',
    authDomain: 'health-ml-app.firebaseapp.com',
    storageBucket: 'health-ml-app.firebasestorage.app',
    measurementId: 'G-EXJVGG62F0',
  );
}
